name: Update README

on:
  schedule:
    - cron: "0 * * * *"   # 每小时更新一次
  workflow_dispatch:       # 支持手动触发

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run update script
        run: python update.py

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add README.md
          git commit -m "auto update" || echo "No changes"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/MonsterTower/MonsterTower.git HEAD:main
